name: Stream A
on:
  schedule:
    # يشعل أوتوماتيكياً كل يوم في هذه الأوقات بالدقيقة 10 ليسبق الحساب الآخر
    - cron: '10 3,7,11,15,19,23 * * *'
  workflow_dispatch: # لتشغيله بيدك دابا أول مرة مع 11:10
jobs:
  stream-a:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update -qq && sudo apt-get install -y ffmpeg -qq
    - run: timeout 4h 10m ffmpeg -re -stream_loop -1 -i 'https://github.com/Alex44364/youtube-live-stream/releases/download/v1/InShot_20260824_122903219.mp4' -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -f flv 'rtmp://a.rtmp.youtube.com/live2/3g7j-2yx1-wp1h-0zgy-6dbd'

